server:
  port: 8083


spring:
  profiles:
    active: test

---

spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/carServer;MODE=MYSQL;
    username: sa
    password:

  sql:
    init:
      mode: always

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packagesToScan: com.carserver
  pathsToMatch: /api/**