INSERT INTO CATEGORY(NAME)
VALUES ('소형');
INSERT INTO CATEGORY(NAME)
VALUES ('준중형');
INSERT INTO CATEGORY(NAME)
VALUES ('중형');
INSERT INTO CATEGORY(NAME)
VALUES ('대형');
INSERT INTO CATEGORY(NAME)
VALUES ('경차');
INSERT INTO CATEGORY(NAME)
VALUES ('세단');
INSERT INTO CATEGORY(NAME)
VALUES ('SUV');
INSERT INTO CATEGORY(NAME)
VALUES ('패밀리카');

--

INSERT INTO CAR (BRAND, MODEL, PRODUCTION_YEAR, RENTAL_STATUS, CREATED_DATE, UPDATED_DATE)
VALUES ('현대', '코나', 2019, 'AVAILABLE', NOW(), NOW());

INSERT INTO CAR (BRAND, MODEL, PRODUCTION_YEAR, RENTAL_STATUS, CREATED_DATE, UPDATED_DATE)
VALUES ('현대', '싼타페', 2020, 'LOST', NOW(), NOW());

INSERT INTO CAR (BRAND, MODEL, PRODUCTION_YEAR, RENTAL_STATUS, CREATED_DATE, UPDATED_DATE)
VALUES ('현대', '아반떼', 2021, 'RENTED', NOW(), NOW());

INSERT INTO CAR (BRAND, MODEL, PRODUCTION_YEAR, RENTAL_STATUS, CREATED_DATE, UPDATED_DATE)
VALUES ('현대', '그랜저', 2022, 'REPAIR', NOW(), NOW());

INSERT INTO CAR (BRAND, MODEL, PRODUCTION_YEAR, RENTAL_STATUS, CREATED_DATE, UPDATED_DATE)
VALUES ('기아', '셀토스', 2022, 'REPAIR', NOW(), NOW());

--

INSERT INTO CAR_CATEGORY (CAR_ID, CATEGORY_ID)
SELECT C.ID, CAT.ID
FROM CAR C,
     CATEGORY CAT
WHERE C.MODEL = '코나'
  AND CAT.NAME IN ('소형', 'SUV');

INSERT INTO CAR_CATEGORY (CAR_ID, CATEGORY_ID)
SELECT C.ID, CAT.ID
FROM CAR C,
     CATEGORY CAT
WHERE C.MODEL = '싼타페'
  AND CAT.NAME IN ('중형', 'SUV', '패밀리카');

INSERT INTO CAR_CATEGORY (CAR_ID, CATEGORY_ID)
SELECT C.ID, CAT.ID
FROM CAR C,
     CATEGORY CAT
WHERE C.MODEL = '아반떼'
  AND CAT.NAME IN ('소형', '세단');

INSERT INTO CAR_CATEGORY (CAR_ID, CATEGORY_ID)
SELECT C.ID, CAT.ID
FROM CAR C,
     CATEGORY CAT
WHERE C.MODEL = '그랜저'
  AND CAT.NAME IN ('대형', '세단');

INSERT INTO CAR_CATEGORY (CAR_ID, CATEGORY_ID)
SELECT C.ID, CAT.ID
FROM CAR C,
     CATEGORY CAT
WHERE C.MODEL = '셀토스'
  AND CAT.NAME IN ('준중형', 'SUV');